# Generated by Django 3.1.2 on 2020-10-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0006_remove_profile_is_trusted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name', 'first_name', 'username')},
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
    ]
