# Generated by Django 3.1.2 on 2021-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0004_auto_20210604_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='long',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zoom',
        ),
        migrations.AddField(
            model_name='profile',
            name='immutable',
            field=models.BooleanField(default=False, help_text='Fields cannot be changes', verbose_name='Immutable'),
        ),
    ]
