# Generated by Django 3.1.2 on 2020-11-07 19:07

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messaggi'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Short bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yes_spam',
            field=models.BooleanField(default=False, help_text='Do you want to be notified on new articles?', verbose_name='Mailing list'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='attachment',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=users.models.user_private_directory_path, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='body',
            field=models.TextField(verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='recipient',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
    ]
