# Generated by Django 3.0.2 on 2020-01-29 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Solo se minore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_parent', to=settings.AUTH_USER_MODEL, verbose_name='Genitore'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sector',
            field=models.CharField(choices=[('0-NO', 'No'), ('3-FI', 'No, solo i figli'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso'), ('4-MI', 'Minore')], default='0-NO', max_length=4, verbose_name='Vuoi correre con noi?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sector',
            field=models.CharField(choices=[('0-NO', 'No'), ('3-FI', 'No, solo i figli'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso'), ('4-MI', 'Minore')], default='0-NO', max_length=4, verbose_name='Corre con noi?'),
        ),
    ]
