# Generated by Django 3.0.4 on 2020-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Breve biografia'),
        ),
    ]
