# Generated by Django 3.1.2 on 2021-06-04 18:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitudine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='profile',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitudine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zoom',
            field=models.FloatField(blank=True, help_text='Al massimo 23', null=True, verbose_name='Fattore di zoom'),
        ),
    ]
