# Generated by Django 3.0.4 on 2020-04-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='no_spam',
        ),
        migrations.AddField(
            model_name='profile',
            name='yes_spam',
            field=models.BooleanField(default=False, help_text='Vuoi ricevere notifiche sugli eventi?', verbose_name='Mailing list'),
        ),
    ]
