# Generated by Django 3.1.2 on 2020-11-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201107_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='Privacy'),
        ),
    ]
