# Generated by Django 3.1.2 on 2021-06-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210604_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=41.8988, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long',
            field=models.FloatField(default=12.5451, verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zoom',
            field=models.FloatField(default=10, help_text='10 is good for a large city', verbose_name='Fattore di zoom'),
        ),
    ]
