# Generated by Django 3.1.2 on 2021-12-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211126_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='immutable',
        ),
    ]
