# Generated by Django 3.1.2 on 2022-01-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='immutable',
            field=models.BooleanField(default=False),
        ),
    ]
