# Generated by Django 3.1.2 on 2021-06-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210604_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitudine'),
        ),
    ]
