# Generated by Django 3.0.2 on 2020-01-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200129_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='sector',
            field=models.CharField(choices=[('0-NO', 'No'), ('3-FI', 'No, solo i figli'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso')], default='0-NO', max_length=4, verbose_name='Vuoi correre con noi?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sector',
            field=models.CharField(choices=[('0-NO', 'No'), ('3-FI', 'No, solo i figli'), ('1-YC', 'Sì, con il corso'), ('2-NC', 'Sì, senza corso')], default='0-NO', max_length=4, verbose_name='Corre con noi?'),
        ),
    ]
