# Generated by Django 3.1.1 on 2020-09-19 11:02

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200702_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='attachment',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=users.models.user_private_directory_path, verbose_name='Allegato'),
        ),
    ]
