# Generated by Django 3.1.2 on 2020-10-27 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201027_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uuid',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
    ]
