# Generated by Django 3.0.2 on 2020-02-01 10:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200129_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Allegato'),
        ),
    ]
