# Generated by Django 3.1.2 on 2020-10-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200919_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_trusted',
        ),
    ]
