# Generated by Django 3.0.2 on 2020-02-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
