# Generated by Django 3.0.2 on 2020-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_applicant_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='no_spam',
            field=models.BooleanField(default=True, help_text='Vuoi ricevere notifiche sugli eventi?', verbose_name='Mailing list'),
        ),
    ]
