# Generated by Django 3.0.4 on 2020-03-22 16:49

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('success', 'Verde'), ('warning', 'Giallo'), ('danger', 'Rosso'), ('primary', 'Blu'), ('secondary', 'Grigio')], default='success', max_length=10, verbose_name='Colore')),
                ('body', models.TextField(help_text='Accetta tag HTML', null=True, verbose_name='Testo')),
            ],
            options={
                'verbose_name': 'Testo in un box',
                'verbose_name_plural': 'Testi in un box',
            },
        ),
        migrations.CreateModel(
            name='CaptionedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia')),
            ],
            options={
                'verbose_name': 'Immagine con didascalia',
                'verbose_name_plural': 'Immagini con didascalia',
            },
        ),
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_file', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'File scaricabile',
                'verbose_name_plural': 'File scaricabili',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia')),
            ],
            options={
                'verbose_name': 'Galleria di immagini',
                'verbose_name_plural': 'Galleria di immagini',
            },
        ),
        migrations.CreateModel(
            name='HomeButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Titolo')),
                ('subtitle', models.CharField(max_length=200, null=True, verbose_name='Sottotitolo')),
                ('link', models.URLField(null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Pulsante di Home Page',
                'verbose_name_plural': 'Pulsanti di Home Page',
            },
        ),
        migrations.CreateModel(
            name='IndexedParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(choices=[('1', 'Troppo grande'), ('2', 'Molto grande'), ('3', 'Grande'), ('4', 'Medio'), ('5', 'Piccolo'), ('6', 'Molto piccolo')], default='4', max_length=1, verbose_name='Altezza titolo')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo')),
                ('body', models.TextField(blank=True, help_text='Accetta tag HTML', null=True, verbose_name='Testo')),
                ('parent_type', models.IntegerField(editable=False, null=True)),
                ('parent_id', models.IntegerField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Paragrafo indicizzato',
                'verbose_name_plural': 'Paragrafi indicizzati',
            },
        ),
        migrations.CreateModel(
            name='LandscapeGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia')),
            ],
            options={
                'verbose_name': 'Galleria di immagini orizzontali',
                'verbose_name_plural': 'Galleria di immagini orizzontali',
            },
        ),
        migrations.CreateModel(
            name='LinkableList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True, verbose_name='Elemento')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Lista con link',
                'verbose_name_plural': 'Liste con link',
            },
        ),
    ]
