# Generated by Django 3.0.2 on 2020-02-06 22:54

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Immagine con didascalia',
                'verbose_name_plural': 'Immagini con didascalia',
            },
        ),
        migrations.CreateModel(
            name='IndexedParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paragrafo indicizzato',
                'verbose_name_plural': 'Paragrafi indicizzati',
            },
        ),
    ]
