# Generated by Django 3.0.4 on 2020-03-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscapegallery',
            name='title',
            field=models.CharField(blank=True, help_text='Appare molto grande', max_length=100, null=True, verbose_name='Titolo'),
        ),
    ]
