# Generated by Django 3.0.4 on 2020-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Titolo')),
                ('subtitle', models.CharField(max_length=200, null=True, verbose_name='Sottotitolo')),
                ('link', models.URLField(null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Pulsante di Home Page',
                'verbose_name_plural': 'Pulsanti di Home Page',
            },
        ),
    ]
