# Generated by Django 3.0.4 on 2020-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0002_homebutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxedtext',
            name='body',
            field=models.TextField(help_text='Accetta tag HTML', null=True, verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='boxedtext',
            name='color',
            field=models.CharField(choices=[('success', 'Verde'), ('warning', 'Giallo'), ('danger', 'Rosso'), ('primary', 'Blu'), ('secondary', 'Grigio')], default='success', max_length=10, verbose_name='Colore'),
        ),
    ]
