# Generated by Django 3.0.2 on 2020-02-07 17:52

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0002_indexedparagraph_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_file', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'File scaricabile',
                'verbose_name_plural': 'File scaricabili',
            },
        ),
        migrations.AlterField(
            model_name='captionedimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia'),
        ),
        migrations.AlterField(
            model_name='indexedparagraph',
            name='body',
            field=models.TextField(blank=True, help_text='Accetta tag HTML', null=True, verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='indexedparagraph',
            name='height',
            field=models.CharField(choices=[('1', 'Troppo grande'), ('2', 'Molto grande'), ('3', 'Grande'), ('4', 'Medio'), ('5', 'Piccolo'), ('6', 'Molto piccolo')], default='4', max_length=1, verbose_name='Altezza titolo'),
        ),
        migrations.AlterField(
            model_name='indexedparagraph',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titolo'),
        ),
    ]
