# Generated by Django 3.0.4 on 2020-03-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0002_landscapegallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexedparagraph',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='indexedparagraph',
            name='parent_type',
        ),
    ]
