# Generated by Django 3.0.4 on 2020-03-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0003_auto_20200320_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedparagraph',
            name='parent_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='indexedparagraph',
            name='parent_type',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
