# Generated by Django 3.0.2 on 2020-02-07 18:31

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0003_auto_20200207_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionedimage',
            name='fb_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='downloadablefile',
            name='fb_file',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='File'),
        ),
    ]
