# Generated by Django 3.0.2 on 2020-02-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0004_auto_20200207_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkableList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True, verbose_name='Elemento')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Lista con link',
                'verbose_name_plural': 'Liste con link',
            },
        ),
    ]
