# Generated by Django 3.0.4 on 2020-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treepage',
            name='navigation',
            field=models.BooleanField(default=True, verbose_name='Mostra navigazione'),
        ),
    ]
