# Generated by Django 3.1.2 on 2021-10-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ('position',), 'verbose_name': 'Immagine', 'verbose_name_plural': 'Immagini'},
        ),
        migrations.AlterModelOptions(
            name='homebutton',
            options={'ordering': ('position',), 'verbose_name': 'Pulsante di Home Page', 'verbose_name_plural': 'Pulsanti di Home Page'},
        ),
        #migrations.RemoveField(
            #model_name='galleryimage',
            #name='prog',
        #),
    ]
