# Generated by Django 3.0.4 on 2020-03-21 14:18

from django.db import migrations, models
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=50, verbose_name='Titolo')),
            ],
            options={
                'verbose_name': 'Pagina ad albero',
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='action',
            field=streamfield.fields.StreamField(blank=True, default='[]', help_text='Link a pagine sponsorizzate.', null=True, verbose_name='Pulsanti di azione'),
        ),
    ]
