# Generated by Django 3.0.4 on 2020-03-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_treepage_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='treepage',
            name='stream_rendered',
            field=models.TextField(editable=False, null=True),
        ),
    ]
