# Generated by Django 3.0.4 on 2020-03-21 15:29

from django.db import migrations, models
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200321_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treepage',
            options={'verbose_name': 'Pagina ad albero', 'verbose_name_plural': 'Pagine ad albero'},
        ),
        migrations.AddField(
            model_name='treepage',
            name='intro',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Introduzione'),
        ),
        migrations.AddField(
            model_name='treepage',
            name='last_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='treepage',
            name='slug',
            field=models.SlugField(help_text="Titolo come appare nell'indirizzo della pagina,\n            solo lettere minuscole e senza spazi", null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='treepage',
            name='stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Testo'),
        ),
        migrations.AddField(
            model_name='treepage',
            name='summary',
            field=models.BooleanField(default=True, verbose_name='Mostra sommario'),
        ),
    ]
