# Generated by Django 3.1.2 on 2020-11-16 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201106_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='homebutton',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=models.TextField(blank=True, help_text='Talk about this website', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, help_text='Appears on first image', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='treepage',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='treepage',
            name='intro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='treepage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Title as it appears in the address bar,\n            only lowercase, no blank spaces', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='treepage',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
