# Generated by Django 3.1.2 on 2021-10-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_activity_project'),
        ('pages', '0002_auto_20211020_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='prog',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='portfolio.project'),
        ),
    ]
