# Generated by Django 3.0.4 on 2020-03-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_treepage_stream_rendered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treepage',
            old_name='stream_rendered',
            new_name='stream_search',
        ),
    ]
