# Generated by Django 3.0.4 on 2020-03-21 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200321_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePagePath',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.TreePage')),
                ('path', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
