# Generated by Django 3.1.2 on 2020-10-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200330_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=models.TextField(blank=True, help_text='Un testo di presentazione', null=True, verbose_name='Testo'),
        ),
    ]
