# Generated by Django 3.1.2 on 2020-10-19 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ('-date',), 'verbose_name': 'Home Page'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='action',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='id',
        ),
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data:'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, help_text='Non appare sul sito', max_length=50, null=True, verbose_name='Titolo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HomeButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Titolo')),
                ('subtitle', models.CharField(max_length=200, null=True, verbose_name='Sottotitolo')),
                ('link', models.URLField(null=True, verbose_name='Link')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Posizione')),
                ('home', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_button', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Pulsante di Home Page',
                'verbose_name_plural': 'Pulsanti di Home Page',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Posizione')),
                ('home', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_image', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Galleria di immagini',
                'verbose_name_plural': 'Galleria di immagini',
            },
        ),
    ]
