# Generated by Django 3.0.4 on 2020-03-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_treepagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treepage',
            name='slug',
            field=models.SlugField(help_text="Titolo come appare nell'indirizzo della pagina,\n            solo lettere minuscole e senza spazi", null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='TreePagePath',
        ),
    ]
