# Generated by Django 3.1.2 on 2020-10-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201019_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Immagine', 'verbose_name_plural': 'Immagini'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, help_text='Compare sulla prima immagine', max_length=50, null=True, verbose_name='Titolo'),
        ),
    ]
