# Generated by Django 3.0.4 on 2020-03-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200322_0102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institutional',
        ),
    ]
