# Generated by Django 3.1.2 on 2020-10-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20201020_1700'),
        ('pages', '0007_auto_20201020_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(editable=False, max_length=200, null=True, upload_to='uploads/portfolio/projects/', verbose_name='Immagine'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='prog',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='portfolio.project'),
        ),
    ]
