# Generated by Django 3.1.2 on 2020-10-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201020_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(editable=False, max_length=200, null=True, upload_to='uploads/images/galleries/', verbose_name='Immagine'),
        ),
    ]
