# Generated by Django 3.1.2 on 2020-10-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_galleryimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treepage',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='treepage',
            name='stream_search',
        ),
        migrations.AddField(
            model_name='treepage',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Testo'),
        ),
    ]
