# Generated by Django 3.1.2 on 2020-10-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20201022_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treepage',
            name='intro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Introduzione'),
        ),
    ]
