# Generated by Django 3.1.2 on 2020-10-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201022_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='treepage',
            name='paragraphs',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
