# Generated by Django 3.1.2 on 2020-10-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(default='Un altro articolo di approfondimento da Startup Project!', max_length=100, verbose_name='Introduzione'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='body',
            field=models.CharField(help_text='Scrivi qualcosa.', max_length=500, verbose_name='Testo'),
        ),
    ]
