# Generated by Django 3.1.2 on 2020-10-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0010_auto_20201025_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userupload',
            name='user',
        ),
    ]
