# Generated by Django 3.0.4 on 2020-03-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stream_rendered',
            field=models.TextField(editable=False, null=True),
        ),
    ]
