# Generated by Django 3.1.2 on 2020-10-30 19:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201030_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(default=blog.models.default_intro, max_length=100, verbose_name='Introduzione'),
        ),
    ]
