# Generated by Django 3.1.2 on 2020-11-04 21:22

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20201030_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='userupload',
            options={'ordering': ('-id',), 'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
        migrations.AlterModelOptions(
            name='uuidtaggeditem',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(default=blog.models.default_intro, max_length=100, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='article',
            name='notice',
            field=models.CharField(blank=True, choices=[('NOSP', 'Do not send'), ('SPAM', 'To be sent'), ('DONE', 'Already sent')], help_text="Send automatic notification by selecting\n            'Send notification' and saving the article.\n            ", max_length=4, null=True, verbose_name='Notify by email'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Comma separated list of categories', through='blog.UUIDTaggedItem', to='taggit.Tag', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='The title of the article', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='body',
            field=models.CharField(help_text='Write something.', max_length=500, verbose_name='Testo'),
        ),
    ]
