# Generated by Django 3.0.4 on 2020-03-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_stream_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stream_rendered',
        ),
    ]
