# Generated by Django 3.1.2 on 2020-10-21 18:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_stream_rendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='article',
            name='stream_search',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(null=True, verbose_name='Testo'),
        ),
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(default='Un altro articolo di approfondimento da architettura.APP!', max_length=100, verbose_name='Introduzione'),
        ),
    ]
