# Generated by Django 3.1.2 on 2020-10-21 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_userupload_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_uploads', to='blog.article'),
        ),
    ]
