# Generated by Django 3.0.4 on 2020-03-12 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
import streamfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Immagine')),
                ('carousel', streamfield.fields.StreamField(blank=True, default='[]', help_text='Una sola galleria, per favore, larghezza minima immagini 2048px', null=True, verbose_name='Galleria')),
                ('title', models.CharField(help_text="Il titolo dell'articolo", max_length=50, verbose_name='Titolo')),
                ('slug', models.SlugField(editable=False, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('last_updated', models.DateTimeField(editable=False, null=True)),
                ('intro', models.CharField(default='Un altro articolo di approfondimento da RP!', max_length=100, verbose_name='Introduzione')),
                ('stream', streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Testo')),
                ('notice', models.CharField(blank=True, choices=[('NOSP', 'Non inviare'), ('SPAM', 'Da inviare'), ('DONE', 'Già inviata')], help_text="Non invia in automatico, per farlo seleziona l'Evento\n            dalla Lista degli Eventi, imposta l'azione 'Invia notifica' e fai\n            clic su 'Vai'.\n            ", max_length=4, null=True, verbose_name='Notifica via email')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Institutional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('3-PR', 'Privacy')], max_length=4, null=True, verbose_name='Tipo')),
                ('title', models.CharField(max_length=50, verbose_name='Titolo')),
                ('intro', models.TextField(blank=True, max_length=200, null=True, verbose_name='Introduzione')),
                ('stream', streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Testo')),
            ],
            options={
                'verbose_name': 'Pagina istituzionale',
                'verbose_name_plural': 'Pagine istituzionali',
            },
        ),
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/blogs/users/', verbose_name='Immagine')),
                ('body', models.TextField(help_text='Scrivi qualcosa.', verbose_name='Testo')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_uploads', to='pagine.Blog')),
            ],
            options={
                'verbose_name': 'Contributo',
                'verbose_name_plural': 'Contributi',
                'ordering': ('-id',),
            },
        ),
    ]
