# Generated by Django 3.0.2 on 2020-01-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('id',), 'verbose_name': 'Luogo', 'verbose_name_plural': 'Luoghi'},
        ),
    ]
