# Generated by Django 3.0.2 on 2020-02-04 07:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0002_auto_20200129_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='chronicle',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Al momento nessuna cronaca disponibile', verbose_name='Cronaca'),
        ),
    ]
