# Generated by Django 3.0.4 on 2020-03-14 14:31

from django.db import migrations, models
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0002_auto_20200312_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel', streamfield.fields.StreamField(blank=True, default='[]', help_text='Una sola galleria, per favore, larghezza minima immagini 2048px', null=True, verbose_name='Galleria')),
                ('intro', models.CharField(blank=True, help_text='Il sito in due parole', max_length=100, null=True, verbose_name='Sottotitolo')),
                ('action', streamfield.fields.StreamField(blank=True, default='[]', help_text='Link a pagine sponsorizzate.', null=True, verbose_name='Pulsanti di azione')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
        ),
    ]
