# Generated by Django 3.0.4 on 2020-03-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0004_auto_20200314_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fb_image',
        ),
    ]
