# Generated by Django 3.0.2 on 2020-02-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0006_auto_20200206_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageEntry',
        ),
    ]
