# Generated by Django 3.0.4 on 2020-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0006_auto_20200320_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutional',
            name='type',
        ),
        migrations.AlterField(
            model_name='institutional',
            name='slug',
            field=models.SlugField(help_text="Titolo come appare nell'indirizzo della pagina,\n            solo lettere minuscole e senza spazi", null=True, unique=True, verbose_name='Slug'),
        ),
    ]
