# Generated by Django 3.0.4 on 2020-03-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0007_auto_20200320_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userupload',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='UserUpload',
        ),
    ]
