# Generated by Django 3.0.2 on 2020-02-07 12:35

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0007_delete_imageentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Blocchi'),
        ),
    ]
