# Generated by Django 3.0.2 on 2020-02-07 13:25

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0009_auto_20200207_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chronicle',
        ),
        migrations.RemoveField(
            model_name='event',
            name='restricted',
        ),
        migrations.AddField(
            model_name='event',
            name='chron_stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Cronaca'),
        ),
        migrations.AddField(
            model_name='event',
            name='restr_stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', help_text='Inserisci qui materiale riservato ai soci', verbose_name='Area riservata'),
        ),
    ]
