# Generated by Django 3.0.2 on 2020-02-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0010_auto_20200207_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventupgrade',
            name='body',
            field=models.TextField(help_text='Accetta tag HTML.', verbose_name='Aggiornamento'),
        ),
    ]
