# Generated by Django 3.0.2 on 2020-02-07 18:41

from django.db import migrations
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagine', '0011_auto_20200207_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='stream',
            field=streamfield.fields.StreamField(blank=True, default='[]', verbose_name='Testo'),
        ),
    ]
