# Generated by Django 3.0.4 on 2020-03-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_treepage_navigation'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_type', models.CharField(max_length=50)),
                ('stream_id', models.IntegerField()),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_stream_helper', to='blog.Article')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_stream_helper', to='pages.TreePage')),
            ],
        ),
    ]
