# Generated by Django 3.0.4 on 2020-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamhelper',
            name='article',
        ),
        migrations.RemoveField(
            model_name='streamhelper',
            name='page',
        ),
        migrations.AddField(
            model_name='streamhelper',
            name='obj_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='streamhelper',
            name='obj_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='streamhelper',
            name='stream_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='streamhelper',
            name='stream_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
